maintainer       "Keno Fischer"
maintainer_email "kfischer@college.harvard.edu"
license          "MIT"
description      "Installs the shipyard as a docker-container"
version          "0.1"
depends 	 "docker"
